version: '3.8'

services:
  api:
    container_name: flask-api
    build: ./api
    volumes:
      - ./api/:/app/
    ports:
      - 5000:5000
  frontend:
    container_name: react-frontend
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/app/
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  node_modules: